apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd-master
  name: nfd-master
  namespace: openshift-cluster-nfd-operator
spec:
  selector:
    matchLabels:
      app: nfd-master 
  template:
    metadata:
      labels:
        app: nfd-master 
    spec:
      serviceAccount: nfd-master
      readOnlyRootFilesystem: true
      nodeSelector: 
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
      containers:
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: quay.io/zvonkok/node-feature-discovery:v4.1
          name: nfd-master
          command: ["nfd-master", "--port=12000"]
