apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-nfd-operator-clusterrole
rules:
- apiGroups:
  - rbac.authorization.k8s.io 
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceName:
  - privileged
- apiGroups:
  - nodefeaturediscovery.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
