kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-nfd-operator
  namespace: openshift-cluster-nfd-operator
subjects:
- kind: ServiceAccount
  name: cluster-nfd-operator
roleRef:
  kind: Role
  name: cluster-nfd-operator
  apiGroup: rbac.authorization.k8s.io
