kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-nfd-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: cluster-nfd-operator
  namespace: openshift-cluster-nfd-operator
roleRef:
  kind: ClusterRole
  name: cluster-nfd-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
