apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfd-operator
  namespace: openshift-nfd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nfd-operator
  template:
    metadata:
      labels:
        name: nfd-operator
    spec:
      serviceAccountName: nfd-operator
      containers:
        - name: nfd-operator
          # Replace this with the built image name
          image: quay.io/zvonkok/cluster-nfd-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cluster-nfd-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              value: "openshift-nfd"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cluster-nfd-operator"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]

      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"

