apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-master-server 
  namespace: REPLACE_NAMESPACE
spec:
  operand:
    namespace: node-feature-discovery-operator
    image: quay.io/openshift/origin-node-feature-discovery:4.7
    imagePullPolicy: Always
  workerConfig:
    configData: |    
      sources:
        pci:
          deviceLabelFields:
            - "vendor"
          deviceClassWhitelist:
            - "0200"
            - "03"
            - "12"
      
