apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nfd-worker
  namespace: openshift-cluster-nfd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nfd-worker
subjects:
- kind: ServiceAccount
  name: nfd-worker
  namespace: openshift-cluster-nfd-operator
userNames:
- system:serviceaccount:openshift-cluster-nfd-operator:nfd-worker
