apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: nodefeaturediscoveries.nfd.openshift.io
spec:
  group: nfd.openshift.io
  names:
    kind: NodeFeatureDiscovery
    listKind: NodeFeatureDiscoveryList
    plural: nodefeaturediscoveries
    singular: nodefeaturediscovery
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
