apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodefeaturediscoveries.nodefeaturediscovery.openshift.io
spec:
  group: nodefeaturediscovery.openshift.io
  names:
    kind: NodeFeatureDiscovery
    listKind: NodeFeatureDiscoveryList
    plural: nodefeaturediscoveries
    singular: nodefeaturediscovery
  scope: Namespaced
  version: v1alpha1
