apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: node-feature-discovery-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: The NFD operator creates and maintains the Node Feature Discovery (NFD) on Kubernetes. It detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels.
  displayName: Node Feature Discovery
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - feature-discovery
  - feature-detection
  - node-labels
  links:
  - name: Node Feature Discovery Operator
    url: https://node-feature-discovery-operator.domain
  maintainers:
  - email: openshift-psap@redhat.com
    name: openshift-psap
  maturity: alpha
  provider:
    name: Red Hat
    url: https://github.com/openshift/cluster-nfd-operator
  version: 0.0.0
