apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-nfd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-nfd-operator
  template:
    metadata:
      labels:
        name: cluster-nfd-operator
    spec:
      serviceAccountName: cluster-nfd-operator
      containers:
        - name: cluster-nfd-operator
          # Replace this with the built image name
          image: quay.io/zvonkok/cluster-nfd-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cluster-nfd-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cluster-nfd-operator"
